### ISSUE TITLE
rhel7 support

### ISSUE THREAD

**Issue by nguyen102** [xenago/libnss_shim#1]
Hi, thank you for creating this package. I would like to set this package up on an Amazon Linux 2. Could you provide support for that OS?

Thank you for your time

**Comment by xenago** [comment]
Sure, I created an RPM package for version 1.1.0 and tested with CentOS 7, it seems to work on EL8/EL9-based OS as well.

Presumably should work with AL2 - let me know how it goes when you try it!

**Comment by nguyen102** [comment]
ah perfect, do you have the link to the RPM package? I would love to test it out.

**Comment by xenago** [comment]
Yes, it is linked in the README and published in the latest release:

https://github.com/xenago/libnss_shim/releases/tag/1.1.0

**Comment by nguyen102** [comment]
thank you so much for your help. I tested it on AL 2 and it worked!
