### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by nguyen102** [xenago/libnss_shim#2]
Hi,

Thanks so much for the quick turn around time on support for rhel7. Would you be able to support arm64 as well? I'm trying to get `libnss_shim` working with AL2 arm64 as well.

https://aws.amazon.com/marketplace/pp/prodview-uvnbekaahdaws

Thanks,
Tim

**Comment by xenago** [comment]
Hi Tim,

Sure, an ARM build step has been added to the CI via QEMU.

I tested the newest aarch64 RPM package on a Raspberry Pi 4 inside an EL-based container and it seems to run as expected:

![image](https://github.com/xenago/libnss_shim/assets/11216007/a0eb506a-6b31-4c04-b410-6f978f488862)

Noah

**Comment by nguyen102** [comment]
This worked! Thank you.
