### ISSUE TITLE
amd64 rpm v1.2 install failure

### ISSUE THREAD

**Issue by nguyen102** [xenago/libnss_shim#4]
amd64 rpm v1.2 install fails on Amazon linux 2 ec2 instance. However v1.1 install works correctly. Error for installing v1.2 is shown below.

```
[root@ip-1 v1.2]# curl -sLo libnss_shim.rpm https://github.com/xenago/libnss_shim/releases/download/1.2.0/libnss_shim-1.2.0-1_x86_64.rpm
[root@ip-1 v1.2]# sudo rpm -Uv ./libnss_shim.rpm
error: open of Not failed: No such file or directory
error: open of Found failed: No such file or directory
```

**Comment by xenago** [comment]
The URL above appears to be invalid (note the `.x86` below, vs `_x86` above):

    curl -sLo libnss_shim.rpm https://github.com/xenago/libnss_shim/releases/download/1.2.0/libnss_shim-1.2.0-1.x86_64.rpm

I updated the README with correct URL for x86_64 RPM.
